version: "3"
services:
  scraper:
    build: .
    environment:
      SCHEDULER_DB_HOSTNAME: postgres
      SCHEDULER_DB_PG_PASSWORD: super-secret-password
      SCHEDULER_DB_DBNAME: postgres
    volumes:
      - ./:/app
    depends_on:
      - postgres

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME="Main Org."
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_UNIFIED_ALERTING_ENABLED=false
      - GF_ALERTING_ENABLE=false
    volumes:
      - ./grafana_data:/var/lib/grafana

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: super-secret-password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "30012:8081"
    environment:
      - DATABASE_URL=postgres://postgres:super-secret-password@postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres
