version: "3"
services:
  scraper:
    build: .
    environment:
      SCHEDULER_DB_USERNAME: postgres
      SCHEDULER_DB_DBNAME: postgres
      SCHEDULER_DB_HOSTNAME: postgres
      SCHEDULER_DB_PORT: 5432
      SCHEDULER_DB_PG_PASSWORD: super-secret-password
      SNS_ENDPOINT_URL: http://localstack:4566
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: "my-access-key"
      AWS_SECRET_ACCESS_KEY: "my-secret-access-key"
      DREXEL_USERNAME: ${DREXEL_USERNAME}
      DREXEL_PASSWORD: ${DREXEL_PASSWORD}
      DREXEL_MFA_SECRET_KEY: ${DREXEL_MFA_SECRET_KEY}
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - localstack

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME="Main Org."
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_UNIFIED_ALERTING_ENABLED=false
      - GF_ALERTING_ENABLE=false
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_NEWS_NEWS_FEED_ENABLED=false
    volumes:
      - ./grafana_data:/var/lib/grafana

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: super-secret-password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "30012:8081"
    environment:
      - DATABASE_URL=postgres://postgres:super-secret-password@postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres
  
  # Used to imitate AWS services locally
  # We are using SNS in this case for sending error emails
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sns
      - EDGE_PORT=4566
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/create-sns-topic.sh:/etc/localstack/init/ready.d/init-aws.sh"
