apiVersion: batch/v1
kind: CronJob
metadata:
  name: delete-credits-cronjob
spec:
  schedule: "0 5 * * *" # Every night at 05:00
  timeZone: "US/Eastern"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: credits-cache
              persistentVolumeClaim:
                claimName: drexel-scheduler-ratings-pvc
          containers:
            - name: delete-credits-file
              image: busybox
              volumeMounts:
                - name: credits-cache
                  mountPath: /data
              command:
                - "/bin/sh"
                - "-c"
                - |
                  if [ -f /data/credits_cache.json ]; then
                    rm /data/credits_cache.json
                  fi
          restartPolicy: OnFailure
