apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/server-snippet: |
      access_by_lua_block {
        local args = ngx.req.get_uri_args()
        -- Check if we're at the root and the kiosk parameter is missing
        if ngx.var.uri == "/" and not args["kiosk"] then
          args["kiosk"] = ""  -- add kiosk (even if empty)
          local new_query = ngx.encode_args(args)
          return ngx.redirect(ngx.var.scheme .. "://" .. ngx.var.host .. "/?" .. new_query, 302)
        end
      }
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.serviceName }}
                port:
                  number: 80
    - host: www.{{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.serviceName }}
                port:
                  number: 80
  tls:
    - hosts:
        - {{ .Values.host }}
        - www.{{ .Values.host }}
      secretName: {{ .Values.tlsSecretName }}
