replicas: 1
grafana.ini:
  auth.anonymous:
    enabled: true
    org_name: Main Org.
    org_role: Viewer

  unified_alerting:
    enabled: false

  alerting:
    enabled: false

  server:
    root_url: "https://scheduler.zohair.dev"

  panels:
    disable_sanitize_html: true

  news:
    news_feed_enabled: false

  users:
    default_theme: light

persistence:
  enabled: true
  type: pvc
  existingClaim: shared-pvc
  subPath: grafana
