{
 "title": "Scheduler Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "null_ratings", "label": "Show blank ratings?", "query": "Yes, No" },
   {
    "name": "min_rating",
    "label": "Minimum Instructor Rating",
    "query": "0, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0"
   },
   {
    "name": "max_difficulty",
    "label": "Maximum Instructor Difficulty",
    "query": "5.0, 4.5, 4.0, 3.5, 3.0, 2.5, 2.0, 1.5, 1.0, 0"
   },
   {
    "name": "min_num_ratings",
    "label": "Minimum Number of Instructor Ratings",
    "query": "0, 1, 3, 5, 7, 10, 15, 20, 25, 30, 35, 40, 45, 50"
   },
   {
    "name": "course_number_greater_than",
    "label": "Course Number Greater Than",
    "query": "0, 100, 200, 300, 400, 500, 600, 900"
   },
   {
    "name": "course_number_less_than",
    "label": "Course Number Less Than",
    "query": "100, 200, 300, 400, 500, 600, 900, 1000"
   },
   {
    "name": "only_blank_prereqs",
    "label": "Include Courses with Prerequisites?",
    "query": "Yes,No"
   },
   { "name": "allow_null_times", "label": "Show blank times?", "query": "Yes, No" },
   {
    "name": "start_time",
    "label": "Start Time",
    "query": "07:00 AM, 07:30 AM, 08:00 AM, 08:30 AM, 09:00 AM, 09:30 AM, 10:00 AM, 10:30 AM, 11:00 AM, 11:30 AM, 12:00 PM, 12:30 PM, 01:00 PM, 01:30 PM, 02:00 PM, 02:30 PM, 03:00 PM, 03:30 PM, 04:00 PM, 04:30 PM, 05:00 PM, 05:30 PM, 06:00 PM, 06:30 PM, 07:00 PM, 07:30 PM, 08:00 PM, 08:30 PM, 09:00 PM, 09: 30 PM, 10:00 PM"
   },
   {
    "name": "end_time",
    "label": "End Time",
    "query": "07:00 AM, 07:30 AM, 08:00 AM, 08:30 AM, 09:00 AM, 09:30 AM, 10:00 AM, 10:30 AM, 11:00 AM, 11:30 AM, 12:00 PM, 12:30 PM, 01:00 PM, 01:30 PM, 02:00 PM, 02:30 PM, 03:00 PM, 03:30 PM, 04:00 PM, 04:30 PM, 05:00 PM, 05:30 PM, 06:00 PM, 06:30 PM, 07:00 PM, 07:30 PM, 08:00 PM, 08:30 PM, 09:00 PM, 09: 30 PM, 10:00 PM"
   },
   { "name": "show_full_courses", "label": "Show full courses?", "query": "Yes, No" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<style>\n    .btn-primary {\n    color: #fff;\n    background-color: #0d6efd;\n    border-color: #0d6efd;\n    padding: .375rem .75rem;\n    font-size: 1rem;\n    border-radius: .2rem;\n    line-height: 1.5;\n    border: 1px solid transparent;\n    display: inline-block;\n    font-weight: 400;\n    text-align: center;\n    vertical-align: middle;\n    cursor: pointer;\n    -webkit-user-select: none;\n       -moz-user-select: none;\n        -ms-user-select: none;\n            user-select: none;\n}\n\n.btn-primary:hover {\n    color: #fff;\n    background-color: #0b5ed7;\n    border-color: #0a58ca;\n}\n\n.btn-primary:disabled {\n    color: #fff;\n    background-color: #0d6efd;\n    border-color: #0d6efd;\n    opacity: .65;\n    pointer-events: none;\n}\n\n.center {\n  margin: auto;\n  width: 50%;\n  padding: 8px 0px;\n  text-align: center;\n}\n\n\n</style>\n\n<div class=\"center\">\n    <button class=\"btn-primary\" onclick=\"resetFilters()\">Reset</button>\n</div>\n\n<script>\nfunction resetFilters() {\n    const currentUrl = window.location.href;\n    const newUrl = currentUrl.split(\"&\")[0];\n    window.location.href = newUrl + \"&kiosk\";\n}\n</script>\n\n<script>\nif ([\"scheduler.zohair.dev\", \"www.scheduler.zohair.dev\"].includes(window.location.hostname)) {\n    ! function(t, e) {\n        var o, n, p, r;\n        e.__SV || (window.posthog = e, e._i = [], e.init = function(i, s, a) {\n            function g(t, e) {\n                var o = e.split(\".\");\n                2 == o.length && (t = t[o[0]], e = o[1]), t[e] = function() {\n                    t.push([e].concat(Array.prototype.slice.call(arguments, 0)))\n                }\n            }(p = t.createElement(\"script\")).type = \"text/javascript\", p.crossOrigin = \"anonymous\", p.async = !0, p.src = s.api_host.replace(\".i.posthog.com\", \"-assets.i.posthog.com\") + \"/static/array.js\", (r = t.getElementsByTagName(\"script\")[0]).parentNode.insertBefore(p, r);\n            var u = e;\n            for (void 0 !== a ? u = e[a] = [] : a = \"posthog\", u.people = u.people || [], u.toString = function(t) {\n                    var e = \"posthog\";\n                    return \"posthog\" !== a && (e += \".\" + a), t || (e += \" (stub)\"), e\n                }, u.people.toString = function() {\n                    return u.toString(1) + \".people (stub)\"\n                }, o = \"init capture register register_once register_for_session unregister unregister_for_session getFeatureFlag getFeatureFlagPayload isFeatureEnabled reloadFeatureFlags updateEarlyAccessFeatureEnrollment getEarlyAccessFeatures on onFeatureFlags onSessionId getSurveys getActiveMatchingSurveys renderSurvey canRenderSurvey identify setPersonProperties group resetGroups setPersonPropertiesForFlags resetPersonPropertiesForFlags setGroupPropertiesForFlags resetGroupPropertiesForFlags reset get_distinct_id getGroups get_session_id get_session_replay_url alias set_config startSessionRecording stopSessionRecording sessionRecordingStarted captureException loadToolbar get_property getSessionProperty createPersonProfile opt_in_capturing opt_out_capturing has_opted_in_capturing has_opted_out_capturing clear_opt_in_out_capturing debug getPageViewId captureTraceFeedback captureTraceMetric\".split(\" \"), n = 0; n < o.length; n++) g(u, o[n]);\n            e._i.push([i, s, a])\n        }, e.__SV = 1)\n    }(document, window.posthog || []);\n    posthog.init('phc_tn6bp7Vd9Pk33w8M3mYbufsUkAPHcQL0xbIsXFKVbn0', {\n                api_host: 'https://us.i.posthog.com',\n                person_profiles: 'always', // or 'always' to create profiles for anonymous users as well\n                }) \n}\n</script>"
   }
  },
  {
   "title": "Term",
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  CASE \n    WHEN value LIKE 'Fall %' THEN value\n    ELSE \n      CONCAT(\n        SPLIT_PART(value, ' ', 1), \n        ' ', \n        CAST(SPLIT_PART(value, ' ', 2) AS INT) + 1\n      )\n  END AS adjusted_term\nFROM metadata\nWHERE key = 'current_term';"
    }
   ]
  },
  {
   "title": "Last Updated (EST)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value FROM metadata WHERE key = 'last_updated';"
    }
   ]
  },
  {
   "title": "All Courses",
   "type": "table",
   "description": "Data from Drexel Term Master Schedule and Rate My Professors to allow you to make an informed decision before choosing a course.\n\nClick on the filters above the table and the filter icon next to the column name to filter the data. Click on the column name to sort the data.\n\nMost Drexel TMS data is updated every 20 minutes to make sure the data is up to date (particularly the seats taken). Rate My Professors data is updated every week. \n\nNOTE: if the scraper can't scrape certain fields, it will show up as a blank cell.",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT course_id AS \"CRN\", subject_code AS \"Subject Code\", course_number AS \"Course Number\", course_title AS \"Course Title\", section AS \"Section\", instructor_name AS \"Instructor Name\", instructor_rmp_id AS \"RateMyProfessors ID\", avg_rating AS \"Average RMP Rating\", avg_difficulty AS \"Average RMP Difficulty\", num_ratings AS \"Number of RMP Ratings\", enroll AS \"Seats Taken\", max_enroll AS \"Total Seats\", instruction_type AS \"Instruction Type\", instruction_method AS \"Instruction Method\", credits AS \"Credits\", prereqs AS \"Prerequisites\", to_char(start_time, 'HH12:MI AM') AS \"Start Time\", to_char(end_time, 'HH12:MI AM') AS \"End Time\", array_to_string(days, ', ') AS \"Days\"\nFROM all_course_instructor_data\nWHERE \n    (\n        ('$null_ratings' = 'Yes')\n        OR \n        ('$null_ratings' = 'No' AND avg_rating IS NOT NULL)\n    )\n    AND \n    (\n        avg_difficulty IS NULL \n        OR avg_difficulty <= $max_difficulty\n    )\n    AND \n    (\n        avg_rating IS NULL \n        OR avg_rating >= $min_rating\n    )\n    AND \n    (\n        num_ratings IS NULL \n        OR num_ratings >= $min_num_ratings\n    )\n    AND\n    (\n        CASE \n            WHEN course_number ~ E'\\\\d+' THEN \n                CAST(substring(course_number FROM E'\\\\d+') AS INTEGER) > $course_number_greater_than \n                AND CAST(substring(course_number FROM E'\\\\d+') AS INTEGER) < $course_number_less_than\n            ELSE TRUE\n        END\n    )\n    AND \n    (\n        ('$allow_null_times' = 'Yes')\n        OR\n        ('$allow_null_times' = 'No' AND start_time IS NOT NULL AND end_time IS NOT NULL)\n    )\n    AND \n    (\n        start_time IS NULL \n        OR start_time >= CAST('$start_time' AS time)\n    )\n    AND \n    (\n        end_time IS NULL \n        OR end_time <= CAST('$end_time' AS time)\n    )\n    AND \n    (\n        ('$show_full_courses' = 'Yes')\n        OR\n        ('$show_full_courses' = 'No' AND enroll <> 'FULL')\n    )\n    AND\n    (\n        ('$only_blank_prereqs' = 'Yes')\n        OR\n        ('$only_blank_prereqs' = 'No' AND prereqs = '')\n    )\nORDER BY \n    subject_code ASC, \n    CAST(substring(course_number FROM '[0-9]+') AS INTEGER) ASC;"
    }
   ]
  },
  {
   "title": "Total Sections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT COUNT(*) FROM courses;" }
   ]
  },
  {
   "title": "Total Instructors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM instructors;"
    }
   ]
  },
  {
   "title": "# of Instructors Rated on RMP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    COUNT(*)\nFROM \n    instructors\nWHERE \n    num_ratings > 0 AND num_ratings IS NOT NULL;\n"
    }
   ]
  },
  {
   "title": "Average # of Ratings / Instructor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    AVG(num_ratings) AS total_instructor_ratings\nFROM \n    instructors"
    }
   ]
  },
  {
   "title": "Average Instructor Rating (out of 5)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    AVG(avg_rating) AS total_instructor_ratings\nFROM \n    instructors"
    }
   ]
  },
  {
   "title": "Average Instructor Difficulty (out of 5)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    AVG(avg_difficulty) AS total_instructor_ratings\nFROM \n    instructors"
    }
   ]
  },
  {
   "title": "Instruction Method Distribution",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    instruction_method,\n    COUNT(*) AS count\nFROM \n    courses\nGROUP BY \n    instruction_method\nORDER BY COUNT(*) DESC;\n"
    }
   ]
  },
  {
   "title": "Credits Distribution",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    credits,\n    COUNT(*) AS count\nFROM \n    courses\nGROUP BY \n    credits\nORDER BY COUNT(*) DESC;\n"
    }
   ]
  },
  {
   "title": "Class Distribution by Time of Day",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    CASE \n        WHEN start_time >= '05:00:00' AND start_time < '12:00:00' THEN 'Morning'\n        WHEN start_time >= '12:00:00' AND start_time < '17:00:00' THEN 'Afternoon'\n        WHEN start_time >= '17:00:00' AND start_time <= '23:59:59' THEN 'Evening'\n        ELSE 'Undefined'\n    END AS time_of_day,\n    COUNT(*) AS count\nFROM \n    courses\nWHERE\n    start_time IS NOT NULL\nGROUP BY \n    time_of_day;\n"
    }
   ]
  },
  {
   "title": "Class Distribution by Day of Week",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    unnested_days,\n    COUNT(*) AS count\nFROM \n    (\n        SELECT UNNEST(days) AS unnested_days\n        FROM courses\n        WHERE days IS NOT NULL\n    ) AS unnested\nGROUP BY \n    unnested_days\nORDER BY \n    count DESC;\n"
    }
   ]
  },
  {
   "title": "Top 10 Courses with the Most Number of Sections",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT \n    CONCAT(subject_code, ' ', course_number) AS \"Course\",\n    COUNT(*) AS \"Sections\"\nFROM \n    courses\nGROUP BY \n    subject_code, course_number\nORDER BY \n    \"Sections\" DESC\nLIMIT 10;\n"
    }
   ]
  },
  {
   "title": "Top 10 Courses with Lowest Average Difficulty (minimum 5 ratings)",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT \n    course_id AS \"CRN\",\n    CONCAT(subject_code, ' ', course_number) AS \"Course\",\n    instructor_name AS \"Instructor\",\n    avg_difficulty AS \"Average Difficulty\"\nFROM \n    all_course_instructor_data\nWHERE \n    num_ratings >= 5 AND avg_difficulty IS NOT NULL\nORDER BY \n    avg_difficulty ASC\nLIMIT 10;\n"
    }
   ]
  },
  {
   "title": "Contact Information",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 63 },
   "options": {
    "content": "Web: [zohair.dev](https://zohair.dev)\n\nEmail: [zohair.ul.hasan@gmail.com](mailto:zohair.ul.hasan@gmail.com)\n\nCode: [github.com/Zohair-coder/drexel-scraper](https://github.com/Zohair-coder/drexel-scraper)\n\nInstagram: [www.instagram.com/drexelscheduler](https://www.instagram.com/drexelscheduler)\n\nDonate: [www.buymeacoffee.com/zohairr](https://www.buymeacoffee.com/zohairr)"
   }
  }
 ]
}