version: '3'
services:
  scraper:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/workspaces:cached

    command: /bin/sh -c "while sleep 1000; do :; done"
 
