name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main
      - dev

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  KUBECONFIG: ${{ secrets.KUBECONFIG }}
  IMAGE_NAME: zohairr/drexelscheduler-scraper

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker build -t $IMAGE_NAME:$COMMIT_SHA .
          docker push $IMAGE_NAME:$COMMIT_SHA

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and configure kubectl
        run: |
          sudo snap install kubectl --classic
          echo "$KUBECONFIG" | base64 --decode > kubeconfig.yaml

      - name: Set Namespace based on Branch
        run: echo "NAMESPACE=$(if [ "${{ github.ref }}" = "refs/heads/main" ]; then echo 'default'; else echo 'dev'; fi)" >> $GITHUB_ENV

      - name: Deploy to Kubernetes
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          sed -i 's|image:.*|image: '"$IMAGE_NAME:$COMMIT_SHA"'|' k8s/cronjob.yaml
          kubectl apply -n ${{ env.NAMESPACE }} -f k8s/ratings-pvc.yaml --kubeconfig=kubeconfig.yaml 
          kubectl apply -f k8s/cronjob-configmap-${{ env.NAMESPACE }}.yaml --kubeconfig=kubeconfig.yaml
          kubectl apply -n ${{ env.NAMESPACE }} -f k8s/cronjob.yaml --kubeconfig=kubeconfig.yaml
